### ISSUE TITLE
mobile doesnot interactive

### ISSUE THREAD

**Issue by wuyudi** [JerryI/Mathematica-ThreeJS-graphics-engine#10]
goto https://jerryi.github.io/Mathematica-ThreeJS-graphics-engine/

into mobile mode.

![image](https://user-images.githubusercontent.com/30024051/212935087-27a23b94-ad55-4456-8518-b0a861343312.png)

It stuck. (But I don't know the reason.)

**Comment by JerryI** [comment]
I will check the orbit controls parameters, or I guess it doesn't even use OrbitControl component (since this part of the code was borrowed from Mathics project)

**Comment by JerryI** [comment]
I will implement this https://developer.mozilla.org/en-US/docs/Web/API/Touch_events onto of `onDocumentMouseMove` function

**Comment by paulmasson** [comment]
@JerryI you don't need to spend time modifying the Mathics code, but should delete it and implement `OrbitControls` completely. After importing `OrbitControls` you still need to create an instance of the controller and update it. Here's an example from one of my libraries:

https://github.com/paulmasson/mathcell/blob/master/src/render/threejs-template.js#L164

Your demo page works on desktop because the Mathics code is still there. Once that is removed and the new controller is in place, then interactivity will be available on both desktop and mobile.
